---
- name: open ssh inbound from the Ansible Tower host to mao_administrators group
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ansible_tower_sg: sg-74f6d711
    allowed_ip: 52.10.45.129/32
  tasks:   
    - local_action:
        module: ec2_group
        name: mao_administrators
        description: allowing adminstrator access
        #vpc_id: vpc-79af741c
        region: us-west-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ ansible_tower_sg }}"

