---
- name: Create an statsd server on EC2
  hosts: localhost
  connection: local
  gather_facts: False 

  tasks:
  #- include_vars: inventory/ec2_vars.yml

    - name: Create securtity group for statsd host
      ec2_group:
        name: "{{ statsd_security_group }}" 
        description: "{{statsd_security_group_desc }}"
        region: "{{ region }}"
        rules: "{{ statsd_rules }}"
        rules_egress: "{{ statsd_rules_egress }}"
        state: 'present'
    
    - name: Create statsd host
      ec2:
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ statsd_instance_type }}"
        image: "{{ ami_id }}" 
        wait: yes
        group: "{{ statsd_security_group }}"
        instance_tags:
          Name: "{{ statsd_tag_name }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/sdb
            device_type: gp2
            volume_size: 100
            delete_on_termination: true
        user_data: "{{ statsd_user_data }}" 
        exact_count: 1
        count_tag:
          Name: "{{ statsd_tag_name }}"
    
