---
- hosts: security_group_mao_statsd_sg
  sudo: yes

  roles:
  - docker

  tasks:
  - name: run graphite-statsd container
    docker: 
      name: mao-statsd
      image: gengmao/graphite-statsd
      state: running
      volumes: 
        - /ebs_vol/graphite/storage:/opt/graphite/storage:rw
        - /ebs_vol/log:/var/log:rw
      ports:
        - 80:80
        - 2003:2003
        - 8125:8125/udp

