---
# tasks file for docker
- name: check if docker exist
  shell: command -v docker || command -v lxc-docker
  changed_when: False
  ignore_errors: True
  register: docker_exist

- name: install docker 
  shell: curl https://get.docker.com/ | sh
  when: docker_exist.stdout == ""

- name: install pip # see http://askubuntu.com/questions/561377/pip-wont-run-throws-errors-instead
  shell: wget -N https://bootstrap.pypa.io/get-pip.py && python get-pip.py

- name: Upgrade latest pip, setuptools, and docker-py with pip
  pip: 
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - setuptools
    - docker-py

