---
- name: open ssh inbound from the Ansible Tower host to mao_administrators group
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:   
    - local_action:
        module: ec2_group
        name: mao_administrators
        description: allowing adminstrator access
        region: us-west-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ ansible_tower_sg }}"

