---
- hosts: security_group_mao_statsd_sg
  sudo: yes
  tasks: 
  - name: Install docker 
    shell: curl https://get.docker.com/ | sh
    register: get_docker 
  - debug: var=get_docker.stdout_lines 

  - name: Run docker
    command: docker run -d -name graphite -v /ebs_vol/graphite/storage:/opt/graphite/storage -v /ebs_vol/log:/var/log -p 80:80 -p 2003:2003 -p 8125:8125/udp gengmao/graphite-statsd
    register: run_docker
  - debug: var=run_docker.stdout_lines

